name: crop_image_widget
description: "A Flutter widget for cropping sections of an image provided by an ImageProvider."
version: 0.0.5
homepage: https://github.com/rozd/crop_image_widget

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  meta: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  mockito: any

flutter:
