name: crop_image_widget
description: "A widget to crop images."
version: 0.0.2
homepage: https://github.com/rozd/crop_image_widget

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  mockito: any

flutter:
